# This workflow integrates Qwiet NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: Qwiet SAST

on:
  pull_request:
  workflow_dispatch:
  push: 

jobs:
  NextGen-Static-Analysis:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Download Qwiet CLI
      run: |
        Invoke-WebRequest -Uri 'https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip' -OutFile sl.zip
        Expand-Archive -Path sl.zip -DestinationPath .


    - name: Restore dependencies
      run: dotnet restore
    - name: Build Jackett App
      run: dotnet build --no-restore

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Analyze with NextGen Static Analysis
      run: .\sl analyze --strict --app Jackett-csharp-demo --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --csharp --dotnet --cpg **/Jackett.sln
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_API_HOST: www.shiftleft.io
        SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
        SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443

    - name: Create status check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: https://app.shiftleft.io/findingsSummary/Jackett-csharp-demo?apps=Jackett-csharp-demo&isApp=1
      run: |
        $params = @{
            Uri         = "https://api.github.com/repos/$ENV:GITHUB_REPOSITORY/check-runs"
            Headers     = @{
              'Authorization' = "Bearer $ENV:GITHUB_TOKEN"
              'Accept' = 'application/vnd.github.antiope-preview+json'
            }
            Method      = 'POST'
            Body        = "{`"name`": `"ShiftLeft NextGen Static Analysis`", `"head_sha`": `"$ENV:GITHUB_REF`", `"external_id`": `"Jackett-csharp-demo`", `"details_url`": `"$ENV:URL`", `"status`": `"completed`", `"conclusion`": `"action_required`", `"output`": {`"title`": `"ShiftLeft NextGen Static Analysis Findings`", `"summary`": `"Visit $ENV:URL for the findings`"}}"
            ContentType = 'application/json'
        }
        Invoke-RestMethod @params

  Build-Rules: 
    runs-on: windows-latest
    needs: NextGen-Static-Analysis
    steps:
    - uses: actions/checkout@v3
    - name: Download ShiftLeft CLI
      run: |
        Invoke-WebRequest -Uri 'https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip' -OutFile sl.zip
        Expand-Archive -Path sl.zip -DestinationPath .
    - name: Validate Build Rules
      run: |
        .\sl check-analysis --app Jackett-csharp-demo `
            --github-pr-number=${{github.event.number}} `
            --github-pr-user=${{ github.repository_owner }} `
            --github-pr-repo=${{ github.event.repository.name }} `
            --github-token=${{ secrets.GITHUB_TOKEN }}
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_API_HOST: www.shiftleft.io
        SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
        SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443
